version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: cra-local
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=cra-db
