name: cra

services:
  postgres:
    image: postgres:16
    container_name: cra
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: cra-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      sh -c "echo '[starting] PostgreSQL container' &&
             docker-entrypoint.sh postgres -c logging_collector=off -c log_destination=stderr -c log_min_messages=warning ||
             echo '[stopped] PostgreSQL container'"

volumes:
  postgres_data: {}

networks:
  postgres_network:
    driver: bridge
